id: P000282
initial_creation_type: ocr
created_at: 20/02/2020
last_modified_at: 2021-12-16 15:10:49.963591
source_metadata:
  id: bdr:W1KG15846
  title: ཀུན་མཁྱེན་པདྨ་དཀར་པོའི་རྣམ་ཐར་སྙན་ངག་ཅན་གྱི་འགྲེལ་བ།
  author: ''
  volumes:
    b2581851922748c28b6ccaf1a8f848a4:
      image_group_id: I1KG15848
      title: Volume 1 of kun mkhyen pad+ma dkar po'i rnam thar snyan ngag can gyi
        'grel ba/
      volume_number: 1
      total_pages: 98
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
