id: opecha:P000282
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG15846
  title: ཀུན་མཁྱེན་པདྨ་དཀར་པོའི་རྣམ་ཐར་སྙན་ངག་ཅན་གྱི་འགྲེལ་བ།
  volume:
    b2581851922748c28b6ccaf1a8f848a4:
      image_group_id: I1KG15848
      title: Volume 1 of kun mkhyen pad+ma dkar po'i rnam thar snyan ngag can gyi
        'grel ba/
      volume_number: 1
      total_pages: 98
  author: ''
ebook_metadata:
  title: ཀུན་མཁྱེན་པདྨ་དཀར་པོའི་རྣམ་ཐར་སྙན་ངག་ཅན་གྱི་འགྲེལ་བ།
  author: ''
  sku: P000282
  cover: cover.jpg
  layers:
  - pagination
